theme: jekyll-theme-leap-day
title: Comparison of Image Enhancement Techniques applied to Sound Data Retrive ( from Images )
description: Final Project for ***USP-SCC 0251/ Processamento de Imagens*** course by Jahir M.